Vagrant.configure(2) do |config|
  # setup proxy
  # dependency: `vagrant plugin install vagrant-proxyconf`

    if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http      = "http://PITC-Zscaler-Americas-Alpharetta3PR.proxy.corporate.ge.com:80"
      config.proxy.https     = "http://PITC-Zscaler-Americas-Alpharetta3PR.proxy.corporate.ge.com:80"
      config.proxy.no_proxy  = "localhost,127.0.0.1,cingetplm099pc.cloud.ge.com"
    end

  config.vm.define "tc-dev" do |tcdev|
    tcdev.vm.box="centos/7"
    tcdev.vm.hostname = "tcdev"
    tcdev.vm.network :private_network, ip: "192.168.100.10"
    tcdev.vm.provision "shell", path: "../createAnsibleUser.sh"
  end

end
